services:
  accounts:
    image: "sysoiev/accounts:section6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice_course
  loans:
    image: "sysoiev/loans:section6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice_course
  cards:
    image: "sysoiev/cards:section6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice_course
networks:
  microservice_course:
    driver: "bridge"